# This is an example of a Makefile
# Indicate that the compiler is the gcc compiler
CC = gcc
# Indicate to the compiler to include header files in the local folder
CPPFLAGS = -I .
calc: calc.o
funcs.o: funcs.c
funcs: funcs.c
main.o : funcs.o 
funcs.o : header.h
